spring:
  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3305/kopring_test?useSSL=false&serverTimezone=Asia/Seoul&autoReconnect=true&rewriteBatchedStatements=true&useServerPrepStmts=false&logger=Slf4JLogger&profileSQL=false&maxQuerySizeToLog=100000
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  exposed:
    generate-ddl: true
    #        show-sql: true
    excluded-packages: com.example.exposedstudy

logging:
  level:
    root: info
    Exposed: info